/* Automation Studio generated header file */
/* Do not edit ! */

#ifndef _LIBRARIES_20230122223756_
#define _LIBRARIES_20230122223756_

__asm__(".section \".plc\"");

/* Used IEC files */
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Convert/Convert.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Convert/Convert.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Convert/Convert.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Runtime/runtime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Runtime/runtime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Runtime/runtime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/brsystem/brsystem.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/brsystem/brsystem.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/brsystem/brsystem.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Standard/standard.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Standard/standard.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Standard/standard.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsString/asstring.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsString/asstring.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsString/asstring.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/DataObj/DataObj.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/DataObj/DataObj.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/DataObj/DataObj.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsTime/astime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsTime/astime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsTime/astime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/CoffeeLib/CoffeeLib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Visapi/Visapi.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Visapi/Visapi.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Visapi/Visapi.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArSdm/AsArSdm.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArSdm/AsArSdm.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArSdm/AsArSdm.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArProf/AsArProf.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArProf/AsArProf.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArProf/AsArProf.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LoopConR/LoopConR.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LoopConR/LoopConR.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LoopConR/LoopConR.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10man/Acp10man.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10par/Acp10par.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/NcGlobal/NcGlobal.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/NcGlobal/NcGlobal.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/NcGlobal/NcGlobal.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10sim/acp10sim.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10sim/acp10sim.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10_MC/acp10_mc.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10_MC/acp10_mc.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10_MC/acp10_mc.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10sdc/acp10sdc.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10sdc/acp10sdc.typ\\\" scope \\\"global\\\"\\n\"");

/* Exported library functions and function blocks */
#ifdef _CONVERT_EXPORT
	__asm__(".ascii \"plcexport \\\"swapDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_SINT\\\" FUN\\n\"");
#endif
#ifdef _RUNTIME_EXPORT
	__asm__(".ascii \"plcexport \\\"r_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"f_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"rf_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetTime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCActionControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCAC2\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RealTan\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAtan\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAsin\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAcos\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealExp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealLn\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealLog\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealExpt\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAbs\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealSin\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealCos\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealSqrt\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCAC3\\\" FUB\\n\"");
#endif
#ifdef _SYS_LIB_EXPORT
	__asm__(".ascii \"plcexport \\\"Byte2Bit\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"Bit2Byte\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KEY_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"KEY_enadis\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_fix\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_copy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_store\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_burn\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_delete\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_write\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_create\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIS_clr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIS_chr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIS_str\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERRxfatal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERR_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERRxread\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERR_fatal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERR_warning\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERRxwarning\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_release\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_attach\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_delete\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_create\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIM_ticks\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIM_musec\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SW_settime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SW_gettime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RTC_settime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RTC_gettime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TMP_free\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TMP_alloc\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MEM_free\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MEM_alloc\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_release\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_attach\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_cancel\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_create\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_sleep\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_exit\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_freemsg\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_recmsg\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_sendmsg\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_resume\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_suspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_name\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_allsuspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_tmp_resume\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_tmp_suspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_resume\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_suspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"FORCE_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MO_ver\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MO_list\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MO_info\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SYS_battery\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SYSreset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SYSxinfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SYS_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xlist\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_ninfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_item\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_list\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xgetval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xsetval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xgetadr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_getadr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_getval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_setval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"slMoList\\\" FUB\\n\"");
#endif
#ifdef _BRSYSTEM_EXPORT
	__asm__(".ascii \"plcexport \\\"MEMInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MEMxInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SysInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RTInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TARGETInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"HWInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SysconfInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SysconfSet\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"BatteryInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"EXCInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ZYKVLenable\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"PMemGet\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"PMemPut\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"PMemSize\\\" FUB\\n\"");
#endif
#ifdef _STANDARD_EXPORT
	__asm__(".ascii \"plcexport \\\"RF_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTUD\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTD\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTU\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"F_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"R_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SR\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RS\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SEMA\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TON\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TOF\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TP\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TON_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TOF_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TP_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LEN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LEFT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RIGHT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MID\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CONCAT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INSERT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DELETE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REPLACE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"FIND\\\" FUN\\n\"");
#endif
#ifdef _ASSTRING_EXPORT
	__asm__(".ascii \"plcexport \\\"ftoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"atof\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"itoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"atoi\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memmove\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memcmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strcat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strlen\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strcmp\\\" FUN\\n\"");
#endif
#ifdef _DATAOBJ_EXPORT
	__asm__(".ascii \"plcexport \\\"DatObjCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjMove\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjCopy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjChangeDate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjAttach\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjDetach\\\" FUB\\n\"");
#endif
#ifdef _FILEIO_EXPORT
	__asm__(".ascii \"plcexport \\\"FileCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileClose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileReadEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileWriteEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileRename\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileCopy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileTruncate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirClose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirReadEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirRename\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirCopy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirDeleteEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SetAttributes\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetAttributes\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevMemInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevLink\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevUnlink\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetVolumeLabel\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetVolumeSerialNo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileIoGetSysError\\\" FUN\\n\"");
#endif
#ifdef _OPERATOR_EXPORT
	__asm__(".ascii \"plcexport \\\"SIZEOF\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADRINST\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SHR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ROR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ROL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SHL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AND\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"XOR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"OR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"NOT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MUL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SUB\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIV\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MOVE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MAX\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LIMIT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SEL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MUX\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EQ\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"NE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ABS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SQRT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LOG\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EXP\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"COS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TAN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ASIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ACOS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ATAN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EXPT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TRUNC\\\" FUN\\n\"");
#endif
#ifdef _ASTIME_EXPORT
	__asm__(".ascii \"plcexport \\\"DTExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"clock_ms\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDT_TO_LocalDTStructure\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LocalDT_TO_UtcDTStructure\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructure_TO_LocalDT\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LocalDTStructure_TO_UtcDT\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ascTIMEStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascDTStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIMEStructure_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_TIMEStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructure_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DTStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DiffT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DiffDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TimeDeviceGetInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DstGetInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DstGetInfoDT\\\" FUB\\n\"");
#endif
#ifdef _COFFEELIB_EXPORT
	__asm__(".ascii \"plcexport \\\"MoneyChanger\\\" FUB\\n\"");
#endif
#ifdef _VISAPI_EXPORT
	__asm__(".ascii \"plcexport \\\"VA_Attach\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_BlitBitmap\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Configure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_CopyScreenRect\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_DelAlarmHistory\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetActiveAlarmCount\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetAlarmCount\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Detach\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_DrawBitmap\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Ellipse\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_ExchangeFont\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_ExtractKeyMatrix\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_FreeBitmap\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetActAlarmList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetAlCurPos\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetAlarmList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetBrightness\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetCalStatus\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetContrast\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetDisplayInfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetExAlarmList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetKeyMatrix\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetPaletteColor\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetPanelStatus\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetTextByTextGroup\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetTouchAction\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_LangIsAvailable\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Line\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_LoadBitmap\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_NGetAlCurPos\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_NGetCalStatus\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_NGetContrast\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_NGetPaletteColor\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Quit\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_QuitAlarms\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Rect\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Redraw\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Saccess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SaveSettings\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetBacklight\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetBrightness\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetClipRegion\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetContrast\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetPaletteColor\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetUserParam\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Setup\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetupX\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Shutdown\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Srelease\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_StartProject\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_StartVisuByName\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_StartTouchCal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_StopProject\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Textout\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_TimeSynchronize\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_wcAlarmGetList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_wcGetActAlarmList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_wcGetExAlarmList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_wcGetTextByTextGroup\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_wcTextout\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetActualLang\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_ClearTouchEventBuffer\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_RegisterClient\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_StartProcess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_TerminateProcess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetProcessExitCode\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetProcessZOrder\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetVisualizationZOrder\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_RunJScript\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetBeep\\\" FUN\\n\"");
#endif
#ifdef _ASARSDM_EXPORT
	__asm__(".ascii \"plcexport \\\"SdmSystemDump\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SdmSetAppParam\\\" FUB\\n\"");
#endif
#ifdef _ASARPROF_EXPORT
	__asm__(".ascii \"plcexport \\\"LogInstall\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LogDeInstall\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LogStateGet\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LogArchCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LogArchDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LogArchCopy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LogArchInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LogStart\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LogStop\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LogEvent\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LogIdleShow\\\" FUB\\n\"");
#endif
#ifdef _LOOPCONR_EXPORT
	__asm__(".ascii \"plcexport \\\"LCRPID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRScal\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRCurveByPoints\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRPIDpara\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRContinServo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRPT1\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRRamp\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRIntegrate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRLimit\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRLimScal\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRPWM\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRMovAvgFlt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRTimeBasedOnOff\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRDifferentiate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRSlimPID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRPIDTune\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRPFM\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRSimModExt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRTt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRPT2\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRPT1e\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRDblActPID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRMinMax\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRTempPID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRTempTune\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRPT2o\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRSchedulePWM\\\" FUB\\n\"");
#endif
#ifdef _NCGLOBAL_EXPORT
	__asm__(".ascii \"plcexport \\\"nccnccom\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncda_dir\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncda_inf\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncda_id\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncda_wr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncda_cr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncaccess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncalloc\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncaction\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ncglobal_action\\\" FUN\\n\"");
#endif
#ifdef _ACP10_MC_EXPORT
	__asm__(".ascii \"plcexport \\\"MC_AbortTrigger\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_AutCommand\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_AutControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_AutoCamDwell\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_AxisErrorCollector\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_BrakeControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_BrakeOperation\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CalcCamFromPoints\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CalcCamFromSections\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CalcPointsFromCam\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CalcSectionsFromCam\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CamIn\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CamDwell\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CamTransition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CheckAutCompensation\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CheckEndlessPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CommandError\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ConfigPowerStageCheck\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CrossCutterControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CyclicRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CyclicReadDataInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_CyclicWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_DigitalCamSwitch\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_DownloadCamProfileObj\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_DownloadCamProfileData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_DownloadParSequ\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_EventMoveAbsolute\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_EventMoveAdditive\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_EventMoveVelocity\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_GearIn\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_GetCamMasterPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_GetCamSlavePosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_GetErrorText\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_GetHardwareInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_GetParIDTransferInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_HomeAcpEncoder\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitAutData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitAutEvent\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitAutPar\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitAutState\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitAxisPar\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitAxisSubjectPar\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitCyclicRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitCyclicWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitEndlessPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitEndlessPosAcpEnc\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitMasterParIDTransfer\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitModPos\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitParList\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitParSequ\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitParTabObj\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitReceiveNetworkData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitReceiveNetworkEnc\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitReceiveParID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_InitSendParID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_JogVelocity\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_JogLimitPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_JogTargetPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_LimitLoad\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_LimitLoadCam\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_LoadAxisPar\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_MoveAbsoluteTriggStop\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_MoveAdditiveTriggStop\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_MoveCyclicPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_MoveCyclicPositionExt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_MoveCyclicVelocity\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_MoveCyclicVelocityExt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_MoveVelocityTriggStop\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_NetTrace\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_NetworkInit\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_Offset\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_OffsetVelocity\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_OffsetZone\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_GetParIDInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ParTrace\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ParTraceConfig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_Phasing\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_MechPosDeviationComp\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_PowerMeter\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadAutPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadAxisError\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadCyclicPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadDriveStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadNetTraceStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadParID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadParIDText\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadParList\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReadParTraceStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ReceiveParIDOnPLC\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_ResetAutPar\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SaveAxisPar\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SaveCamProfileObj\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SetHardwareInputs\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SetupController\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SetupFromParTabObj\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SetupInductionMotor\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SetupIsqRipple\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SetupMotorPhasing\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_SetupSynchronMotor\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_Simulation\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_TouchProbe\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_VelocityControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_WriteParID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_WriteParIDText\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_CamIn\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_CamOut\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_CamTableSelect\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_DigitalCamSwitch\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_GearIn\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_GearInPos\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_GearOut\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_Halt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_Home\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_LimitLoad\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_MoveAbsolute\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_MoveAdditive\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_MoveVelocity\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_Phasing\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_Power\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadActualPosition\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadActualTorque\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadActualVelocity\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadAxisError\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadBoolParameter\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadDigitalInput\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadDigitalOutput\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadParameter\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_ReadStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_Reset\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_SetOverride\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_Stop\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_TouchProbe\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_TorqueControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_BR_TorqueControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_WriteBoolParameter\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_WriteDigitalOutput\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MC_WriteParameter\\\" FUB\\n\"");
#endif

__asm__(".previous");


#endif /* _LIBRARIES_20230122223756_ */

